const mongoose = require("mongoose")

/**
 * A quiz belongs to a course, optionally scoped to one lecture
 * (subSection). Course-level quizzes (subSection unset) act as a final
 * assessment; lecture-level ones check understanding of that specific
 * video. correctOptionIndex is never sent to students — see Quiz.js
 * controller's getQuizForStudent, which strips it before responding.
 */
const questionSchema = new mongoose.Schema(
  {
    questionText: { type: String, required: true },
    options: {
      type: [String],
      required: true,
      validate: (arr) => arr.length >= 2,
    },
    correctOptionIndex: { type: Number, required: true, min: 0 },
    explanation: { type: String },
  },
  { _id: true }
)

const quizSchema = new mongoose.Schema(
  {
    course: { type: mongoose.Schema.Types.ObjectId, ref: "Course", required: true, index: true },
    subSection: { type: mongoose.Schema.Types.ObjectId, ref: "SubSection", default: null },
    title: { type: String, required: true },
    questions: {
      type: [questionSchema],
      validate: (arr) => arr.length > 0,
    },
    passingScorePercent: { type: Number, default: 70, min: 0, max: 100 },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    // Instructor drafts (possibly AI-generated by the copilot) start
    // unpublished — a quiz is never visible to students until an
    // instructor explicitly approves it. Same human-review gate the plan
    // requires for any AI-assisted content.
    published: { type: Boolean, default: false },
  },
  { timestamps: true }
)

module.exports = mongoose.models.Quiz || mongoose.model("Quiz", quizSchema)
